Deprecated cgi in python3 #1330
cherrypy/cherrypy pull request #1513
Opened 2016-10-26 16:30 UTC by paulohrpinheiro

Use import especific to py2 or py3 to escape function from older cgi or newest html module in python3, conform #1330.

2016-10-30 20:00 UTC, webknjaz requested changes
I appreciate the overall idea, but you should fix the pitfalls, I've mentioned.

2016-10-30 20:00 UTC, webknjaz commented on cherrypy/_cpcompat.py
> +if six.PY2:
I'd use try/except ImportError approach. `html.escape()` appeared in 3.2, so it will fail for 3.0-3.1.

2016-10-30 20:00 UTC, webknjaz commented on cherrypy/_cpcompat.py
> +    def escape_html(s):
You break function signature here. It's now impossible to pass custom `quote` argument explicitly. You should accept  `quote=False` and bypass it on call below.

2016-10-30 20:00 UTC, webknjaz commented on cherrypy/_cpcompat.py
> +    from cgi import escape as escape_html
you **must not** fool user with another function name. especially when it's behavior differs. escape_html would be expected to have `quote=True`, whereas you break this expectation.

2016-10-30 20:00 UTC, webknjaz commented on cherrypy/test/test_compat.py
> +        self.assertEqual('xx&amp;&lt;&gt;"aa', compat.escape_html('xx&<>"aa'))
Add tests with passing different `quote=` explicitly.

2016-10-30 20:00 UTC, webknjaz commented on cherrypy/_cpcompat.py
> +    def escape_html(s):
Yet, I'm still unsure which default should we fall back to.
@jaraco, shouldn't we escape html safely?

2016-10-31 14:27 UTC, paulohrpinheiro commented
Hello!


Em 30-10-2016 18:00, Sviatoslav Sydorenko escreveu:
> I appreciate the overall idea, but you should fix the pitfalls, I've
> mentioned.

First of all, I thank the indicated corrections. I hope to make a good 
contribution.


> In cherrypy/_cpcompat.py
> (...)
> +if six.PY2:
>
> I'd use try/except ImportError approach. |html.escape()| appeared in
> 3.2, so it will fail for 3.0-3.1.

OK.


> In cherrypy/_cpcompat.py
> <https://github.com/cherrypy/cherrypy/pull/1513#pullrequestreview-6370151>:
> (...)
> +if six.PY2:
> +    from cgi import escape as escape_html
> +else:
> +    from html import escape
> +
> +    def escape_html(s):
>
> You break function signature here. It's now impossible to pass custom
> |quote| argument explicitly. You should accept |quote=False| and bypass
> it on call below.

See my remarks on the quote parameter below.


> In cherrypy/_cpcompat.py
> <https://github.com/cherrypy/cherrypy/pull/1513#pullrequestreview-6370151>:
> (...)
> +if six.PY2:
> +    from cgi import escape as escape_html
>
> you *must not* fool user with another function name. especially when
> it's behavior differs. escape_html would be expected to have
> |quote=True|, whereas you break this expectation.

OK. Now, escape_html is a function, the try/catch is only to the import. 
The quote argument is a problem. With quote=True I get different results:

[paulohrpinheiro@localhost cherrypy]$ python2
Python 2.7.12 (default, Sep 29 2016, 13:30:34)
[GCC 6.2.1 20160916 (Red Hat 6.2.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
 >>> import cgi
 >>> cgi.escape("""xx&<>"aa'""", quote=True)
"xx&amp;&lt;&gt;&quot;aa'"

[paulohrpinheiro@localhost cherrypy]$ python3
Python 3.5.1 (default, Sep 19 2016, 10:16:17)
[GCC 6.1.1 20160621 (Red Hat 6.1.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
 >>> import html
 >>> html.escape("""xx&<>"aa'""", quote=True)
'xx&amp;&lt;&gt;&quot;aa&#x27;'



> In cherrypy/test/test_compat.py
> <https://github.com/cherrypy/cherrypy/pull/1513#pullrequestreview-6370151>:
> (...)
> Add tests with passing different |quote=| explicitly.

As I said above, quote = True produces different results between PY2 and 
PY3. Because this option is not used, and the current code uses quote = 
False, it is not better to force always quote = False?

I changed to always use quote = False explicitly, but if you think 
otherwise I can change that.

Thanks!

--
Paulo Henrique Rodrigues Pinheiro
https://about.me/paulohrpinheiro

2016-10-31 15:05 UTC, webknjaz requested changes

2016-10-31 15:05 UTC, webknjaz commented on cherrypy/_cpcompat.py
> +except:
catch only `ImportError` here.

2016-10-31 15:05 UTC, webknjaz commented on cherrypy/_cpcompat.py
> +def escape_html(s):
This still needs to have `quote=False`

2016-10-31 15:05 UTC, webknjaz commented on cherrypy/_cpcompat.py
> +    return escape(s, quote=False)
And bypass `quote=quote` into `escape()`

2016-10-31 15:10 UTC, paulohrpinheiro commented on cherrypy/_cpcompat.py
> +except:
Done.

2016-10-31 15:12 UTC, paulohrpinheiro commented on cherrypy/_cpcompat.py
> +def escape_html(s):
Done

2016-10-31 15:12 UTC, paulohrpinheiro commented on cherrypy/_cpcompat.py
> +    return escape(s, quote=False)
Done.

2016-10-31 17:11 UTC, paulohrpinheiro commented
@webknjaz, the fail in travis is a timeout in another piece of code. Please, what I do now?

2016-11-01 07:37 UTC, webknjaz approved these changes

2016-11-01 07:38 UTC, webknjaz commented
It's okay, I've re-run that build and it succeeded.

2016-11-01 07:41 UTC, merged